// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  firebaseConfig: {
    apiKey: 'AIzaSyCwNfkpCgRIeIQvaHRogdZNxCmCPQLNEeg',
    authDomain: 'kiunbitest.firebaseapp.com',
    databaseURL: 'https://kiunbitest.firebaseio.com',
    projectId: 'kiunbitest',
    storageBucket: 'kiunbitest.appspot.com',
    messagingSenderId: '516431274376',
    appId: '1:516431274376:web:fb5517aa286823991bda3d',
  },
  hmr: false,
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'es-ES',
  supportedLanguages: ['es-ES'],
};
